using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SalonAppointmentApi.Data;
using SalonAppointmentApi.Models;

namespace SalonAppointmentApi.Controllers;

[ApiController,Route("api/admin"),Authorize(Roles="Admin,SuperAdmin")]
public sealed class AdminManagementController(AppDbContext db,IWebHostEnvironment env) : ControllerBase
{
 int AdminId=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:0;
 async Task Save(string action,string type,object? id,object? value=null){db.AdminAuditLogs.Add(new AdminAuditLog{AdminUserId=AdminId,Action=action,EntityType=type,EntityId=id?.ToString(),Description=action+" "+type,NewValues=value==null?null:JsonSerializer.Serialize(value),IPAddress=HttpContext.Connection.RemoteIpAddress?.ToString()});await db.SaveChangesAsync();}
 [HttpPatch("users/{id:int}")] public async Task<IActionResult> UpdateUser(int id,UserChange input){var x=await db.AppUsers.FindAsync(id);if(x==null||x.IsDeleted)return NotFound(new{message="User not found."});if(id==AdminId&&input.IsActive==false)return Conflict(new{message="You cannot disable your own account."});if(input.Role!=null){var roles=new[]{"Customer","BusinessOwner","Admin","SuperAdmin"};if(!roles.Contains(input.Role))return BadRequest(new{message="Invalid role."});if(input.Role=="SuperAdmin"&&!User.IsInRole("SuperAdmin"))return Forbid();x.Role=input.Role;}if(input.IsActive.HasValue)x.IsActive=input.IsActive.Value;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Update","User",id,input);return Ok(new{x.Id,x.Role,x.IsActive});}
 [HttpDelete("users/{id:int}")] public async Task<IActionResult> DeleteUser(int id){if(id==AdminId)return Conflict(new{message="You cannot delete your own account."});var x=await db.AppUsers.FindAsync(id);if(x==null||x.IsDeleted)return NotFound(new{message="User not found."});x.IsDeleted=true;x.IsActive=false;x.DeletedAt=DateTime.UtcNow;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Delete","User",id);return NoContent();}
 [HttpDelete("reviews/{id:int}")] public async Task<IActionResult> Review(int id){var x=await db.Reviews.FindAsync(id);if(x==null)return NotFound(new{message="Review not found."});db.Remove(x);await db.SaveChangesAsync();await Save("Delete","Review",id);return NoContent();}
 [HttpPost("employee-services")] public async Task<IActionResult> Assign(EmployeeService x){x.Id=0;if(!await db.Employees.AnyAsync(e=>e.Id==x.EmployeeId)||!await db.Services.AnyAsync(s=>s.Id==x.ServiceId))return BadRequest(new{message="Employee or service not found."});if(await db.EmployeeServices.AnyAsync(a=>a.EmployeeId==x.EmployeeId&&a.ServiceId==x.ServiceId))return Conflict(new{message="Assignment already exists."});db.Add(x);await db.SaveChangesAsync();await Save("Create","EmployeeService",x.Id,x);return Ok(x);}
 [HttpDelete("employee-services/{id:int}")] public async Task<IActionResult> Unassign(int id){var x=await db.EmployeeServices.FindAsync(id);if(x==null)return NotFound(new{message="Assignment not found."});db.Remove(x);await db.SaveChangesAsync();await Save("Delete","EmployeeService",id);return NoContent();}
 [HttpPost("content")] public async Task<IActionResult> Content(ContentItem x){x.Id=0;x.CreatedAt=x.UpdatedAt=DateTime.UtcNow;db.Add(x);await db.SaveChangesAsync();await Save("Create","Content",x.Id,x);return Ok(x);}
 [HttpPut("content/{id:int}")] public async Task<IActionResult> Content(int id,ContentItem v){var x=await db.ContentItems.FindAsync(id);if(x==null)return NotFound(new{message="Content not found."});x.Key=v.Key;x.Title=v.Title;x.Value=v.Value;x.ContentType=v.ContentType;x.Group=v.Group;x.ImageUrl=v.ImageUrl;x.IsActive=v.IsActive;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Update","Content",id,x);return Ok(x);}
 [HttpDelete("content/{id:int}")] public async Task<IActionResult> Content(int id){var x=await db.ContentItems.FindAsync(id);if(x==null)return NotFound(new{message="Content not found."});db.Remove(x);await db.SaveChangesAsync();await Save("Delete","Content",id);return NoContent();}
 [HttpPost("announcements")] public async Task<IActionResult> Announcement(Announcement x){x.Id=0;x.CreatedAt=x.UpdatedAt=DateTime.UtcNow;db.Add(x);await db.SaveChangesAsync();await Save("Create","Announcement",x.Id,x);return Ok(x);}
 [HttpPut("announcements/{id:int}")] public async Task<IActionResult> Announcement(int id,Announcement v){var x=await db.Announcements.FindAsync(id);if(x==null)return NotFound(new{message="Announcement not found."});x.Title=v.Title;x.Body=v.Body;x.StartAt=v.StartAt;x.EndAt=v.EndAt;x.IsActive=v.IsActive;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Update","Announcement",id,x);return Ok(x);}
 [HttpDelete("announcements/{id:int}")] public async Task<IActionResult> Announcement(int id){var x=await db.Announcements.FindAsync(id);if(x==null)return NotFound(new{message="Announcement not found."});db.Remove(x);await db.SaveChangesAsync();await Save("Delete","Announcement",id);return NoContent();}
 [HttpPost("faq")] public async Task<IActionResult> Faq(FaqItem x){x.Id=0;x.CreatedAt=x.UpdatedAt=DateTime.UtcNow;db.Add(x);await db.SaveChangesAsync();await Save("Create","Faq",x.Id,x);return Ok(x);}
 [HttpPut("faq/{id:int}")] public async Task<IActionResult> Faq(int id,FaqItem v){var x=await db.FaqItems.FindAsync(id);if(x==null)return NotFound(new{message="FAQ not found."});x.Question=v.Question;x.Answer=v.Answer;x.SortOrder=v.SortOrder;x.IsActive=v.IsActive;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Update","Faq",id,x);return Ok(x);}
 [HttpDelete("faq/{id:int}")] public async Task<IActionResult> Faq(int id){var x=await db.FaqItems.FindAsync(id);if(x==null)return NotFound(new{message="FAQ not found."});db.Remove(x);await db.SaveChangesAsync();await Save("Delete","Faq",id);return NoContent();}
 [HttpPost("settings")] public async Task<IActionResult> Setting(AppSetting x){x.Id=0;x.UpdatedAt=DateTime.UtcNow;db.Add(x);await db.SaveChangesAsync();await Save("Create","Setting",x.Id,x);return Ok(x);}
 [HttpPut("settings/{id:int}")] public async Task<IActionResult> Setting(int id,AppSetting v){var x=await db.AppSettings.FindAsync(id);if(x==null)return NotFound(new{message="Setting not found."});x.Value=v.Value;x.Description=v.Description;x.DataType=v.DataType;x.Group=v.Group;x.IsPublic=v.IsPublic;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await Save("Update","Setting",id,x);return Ok(x);}
 [HttpPost("media")] [RequestSizeLimit(10_000_000)] public async Task<IActionResult> Media(IFormFile file){if(file.Length==0||file.Length>10_000_000)return BadRequest(new{message="Invalid file."});var allowed=new[]{"image/jpeg","image/png","image/webp","application/pdf"};if(!allowed.Contains(file.ContentType))return BadRequest(new{message="Unsupported file type."});var dir=Path.Combine(env.WebRootPath??Path.Combine(env.ContentRootPath,"wwwroot"),"media");Directory.CreateDirectory(dir);var name=Guid.NewGuid().ToString("N")+Path.GetExtension(file.FileName);await using(var stream=System.IO.File.Create(Path.Combine(dir,name)))await file.CopyToAsync(stream);var x=new MediaAsset{FileName=name,OriginalFileName=Path.GetFileName(file.FileName),Url="/media/"+name,MimeType=file.ContentType,SizeBytes=file.Length,UploadedByAdminUserId=AdminId};db.Add(x);await db.SaveChangesAsync();await Save("Create","Media",x.Id);return Ok(x);}
}
public sealed record UserChange(bool? IsActive,string? Role);
